### ISSUE TITLE
Not all switches showing

### ISSUE THREAD

**Issue by MarketSqHero** [Martvvliet/homebridge-denon-heos#62] opened 2020-10-20 11:00 UTC
Hi;

Finding an odd issue were switches aren't showing. I currently have 5 swtiches and a soft volume control (fan) set in the config. However it only shows the first 4 switches, and doesn't show the last switch (Vinyl) or the volume control. If I reboot the HB I get this in the log

[10/20/2020, 11:56:48] [DenonAVR] New switch configured: TV Audio
[10/20/2020, 11:56:48] [DenonAVR] New switch configured: Apple TV
[10/20/2020, 11:56:48] [DenonAVR] New switch configured: Xbox
[10/20/2020, 11:56:48] [DenonAVR] New switch configured: Playstation
[10/20/2020, 11:56:48] [DenonAVR] Configured switch found: Vinyl
[10/20/2020, 11:56:48] [DenonAVR] Configured volumeControl found: Amp Volume

However, if I then reboot the HB again I get the following message

[10/20/2020, 11:59:03] [DenonAVR] Configured switch found: TV Audio
[10/20/2020, 11:59:03] [DenonAVR] Configured switch found: Apple TV
[10/20/2020, 11:59:03] [DenonAVR] Configured switch found: Xbox
[10/20/2020, 11:59:03] [DenonAVR] Configured switch found: Playstation
[10/20/2020, 11:59:03] [DenonAVR] New switch configured: Vinyl
[10/20/2020, 11:59:03] [DenonAVR] New volumeControl configured: Amp Volume

...and now I get the Vinyl switch, the Amp Volume "fan", but lose the first 4 switches!!!

Any thoughts?

"switches": [
                {
                    "name": "TV Audio",
                    "ip": "192.168.0.110",
                    "inputID": "TV"
                },
                {
                    "name": "Apple TV",
                    "ip": "192.168.0.110",
                    "inputID": "MPLAY"
                },
                {
                    "name": "Xbox",
                    "ip": "192.168.0.110",
                    "inputID": "GAME"
                },
                {
                    "name": "Playstation",
                    "ip": "192.168.0.110",
                    "inputID": "BD"
                },
                {
                    "name": "Vinyl",
                    "ip": "192.168.0.110",
                    "inputID": "CD"
                }
            ],
            "volumeControl": [
                {
                    "name": "Amp Volume",
                    "ip": "192.168.0.110",
                    "controlType": "fan",
                    "volumeLimit": 80
                }
            ],

**Comment by Martvvliet** [comment] 2020-10-22 11:02
@MarketSqHero This is sadly enough a known problem, but I can't reproduce it on my own setup, so didn't have a quick solution for it. Working on it though as I finally have some time now again :)

**Comment by MarketSqHero** [comment] 2020-10-22 11:17
Well that's good news in that it's at least a known issue. As a slight aside it seems that adding either "CBL/SAT" or "SAT/CBL" in the input list, although it shows, doesn't actually change the input when selected. Could this be an issue with the forward slash being a delimiter or something?

On 22 October 2020 at 12:02, Martvvliet <notifications@github.com> wrote:






@MarketSqHero This is sadly enough a known problem, but I can't reproduce it on my own setup, so didn't have a quick solution for it. Working on it though as I finally have some time now again :)

**Comment by Martvvliet** [comment] 2020-10-24 21:02
@MarketSqHero Hmm, interesting. Are you sure that your receiver has the CBL/SAT or the SAT/CBL and it is not disabled?

**Comment by Martvvliet** [comment] 2020-10-30 21:11
@MarketSqHero I made some changes in 2.9.5. Can you verify if you still have the issue with the switches?

**Comment by MarketSqHero** [comment] 2020-11-02 09:05
@Martvvliet Hi, managed to update the plugin last night when I got home, still the same issue with it showing a maximum if 5 switches and each reboot seems to configure the missing ones and add them, and then next reboot it reconfigures back to the other ones.

**Comment by marketsqhero** [comment] 2020-11-05 22:47
Hi;

Not sure what's changed, maybe I needed a full reboot, but everything is working now related to this issue. All inputs are showing, and the Sat/Cbl issues is fixed too. Thanks!

**Comment by Martvvliet** [comment] 2020-11-09 22:08
Great, thanks for letting me know. Will close this now.

**Closed** 2020-11-09 22:08 UTC
